PYTHON = python3
PIP = pip3
APP = main.py

.PHONY: all install run debug clean lint

all: run

install:
	$(PIP) install -r requirements.txt

run:
	$(PYTHON) $(APP)

debug:
	PYTHONASYNCIODEBUG=1 $(PYTHON) -m pdb $(APP)

lint:
	flake8 .
	black --check .

clean:
	find . -type d -name "__pycache__" -exec rm -rf {} +
	find . -type f -name "*.pyc" -delete
	rm -rf .pytest_cache .build